### ISSUE TITLE
After update to 4.3.0 got error 'undefined method `blank?' for "":String'

### ISSUE THREAD

**Issue by shir** [whitesmith/rubycritic#338]
```
$ bundle exec rubycritic
bundler: failed to load command: rubycritic (/Users/shir/.asdf/installs/ruby/2.6.5/bin/rubycritic)
NoMethodError: undefined method `blank?' for "":String
  /Users/shir/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.3.0/lib/rubycritic/source_control_systems/git.rb:55:in `switch_branch'
  /Users/shir/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.3.0/lib/rubycritic/commands/compare.rb:49:in `analyse_branch'
  /Users/shir/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.3.0/lib/rubycritic/commands/compare.rb:34:in `compare_branches'
  /Users/shir/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.3.0/lib/rubycritic/commands/compare.rb:20:in `execute'
  /Users/shir/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.3.0/lib/rubycritic/cli/application.rb:21:in `execute'
  /Users/shir/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.3.0/bin/rubycritic:10:in `<top (required)>'
  /Users/shir/.asdf/installs/ruby/2.6.5/bin/rubycritic:23:in `load'
  /Users/shir/.asdf/installs/ruby/2.6.5/bin/rubycritic:23:in `<top (required)>'
```

I guess issue is that `blank?` method is defined by Ruby on Rails.

**Comment by clive-devops** [comment]
Can confirm, all our builds broke due to this, we've had to hard-exclude 4.3.0, for now, in our Gemfiles until this is fixed.

**Comment by nunosilva800** [comment]
Gonna publish the fix soon.
